# Generated by Django 2.2.10 on 2020-06-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
